name: Publish to PyPI

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version-file: ".python-version"
          cache: true
      - name: pdm install
        run: pdm install --no-lock --no-editable
      - run: pdm build
      - name: pdm publish
        env:
          PDM_PUBLISH_USERNAME: __token__
          PDM_PUBLISH_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: pdm publish --no-build
