name: Publish to Test PyPI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version-file: ".python-version"
          cache: true
      - run: pdm install
      - run: pdm build
      - env:
          PDM_PUBLISH_USERNAME: __token__
          PDM_PUBLISH_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        run: pdm publish --no-build --repository testpypi
